name: Simple GitLab Push

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    push-to-gitlab:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Push to GitLab
              run: |
                  git remote remove gitlab || true
                  git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_REPO_URL }}
                  git push gitlab HEAD:main --force
